### ISSUE TITLE
VScode syntax highlighting

### ISSUE THREAD

**Issue by benshawuk** [racha/alpinejs-jsz#1]
Great plugin, thanks!
Any ideas how to get VScode to highlight the templates, between the curly brackets?
I tried a few things, but it seemed to switch off all other PHP highlighting.
Thanks again!

**Comment by racha** [comment]
Apparently Volar (Vue Language Features) helps with it... try it out. I didn't even notice it was Volar untill now...


https://marketplace.visualstudio.com/items?itemName=Vue.volar
